"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Poppins, Pacifico } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`overflow-x-hidden bg-primary-black min-h-screen ${poppins.className}`}>
        <SessionProvider>
          <Navbar />
          {children}
          <Analytics />
        </SessionProvider>
      </body>
    </html>
  );
}
